### ISSUE TITLE
[BUG] Empty file index during loading layout  qMRI reference dataset

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-matlab#470] opened 2022-11-08 15:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

```Markdown
- Linux Ubuntu 18.04 "bionic beaver"
```

### Platform

- [X] MATLAB
- [ ] Octave

### Platform version

```Markdown
- MATLAB 2017a
```

### bids-matlab version

v0.1.0

### branch / commit number

```Markdown
- main 913246915448505b43c
```

### Current Behavior

While loading layout the [ds-mpm](https://osf.io/k4bs5/) from OSF, the `bids.layout` crashes with `Expected one output from a curly brace or dot indexing expression, but there were 0 results.` error.

From quick invistigation, problem comes from file `sub-01/fmap/sub-01_acq-headMTw_RB1COR.json` during searching dependencies.

The returned `file_info` structure (`layout.m:597) has an empty file_idx:
```matlab
info_dest = 

  struct with fields:

        path: '/Storage/beliy/bidsifications/osf/source/sub-01/fmap'
    filename: 'sub-01_acq-headMTw_RB1COR.json'
     sub_idx: 1
    modality: 'fmap'
    file_idx: [0x1 double]
```

### Error message

```Markdown
>> BIDS = bids.layout('source')
Expected one output from a curly brace or dot indexing expression, but there were 0 results.

Error in bids.layout>manage_dependencies (line 598)
      BIDS.subjects(info_dest.sub_idx).(info_dest.modality)(info_dest.file_idx) ...

Error in bids.layout (line 148)
  BIDS = manage_dependencies(BIDS, verbose);
```

### Anything else?

I will give more details later, so far the bug is quite mistirious.

**Comment by Remi-Gau** [comment] 2022-11-08 16:18
I can reproduce it on the dev branch.

Also getting this error for 'ds-vfa'.

```
bids.layout(fullfile(pwd, 'ds-vfa'))
Dot indexing is not supported for variables of this type.

Error in bids.internal.return_file_index (line 15)
  file_idx = strcmp(filename, {BIDS.subjects(sub_idx).(modality).filename}');

Error in bids.internal.return_file_info (line 20)
  file_info.file_idx = bids.internal.return_file_index(BIDS, ...

Error in bids.layout>manage_dependencies (line 663)
      info_dest = bids.internal.return_file_info(BIDS, dest);

Error in bids.layout (line 170)
  BIDS = manage_dependencies(BIDS, index_dependencies, verbose);
```

**Comment by Remi-Gau** [comment] 2022-11-08 16:33
I don't think this is a bids-matlab issue: the validation is failing.

The intended for is pointing to json files and not .nii files

```bash
bids-validator ds-mpm 
bids-validator@1.9.9
(node:120493) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
        1: [ERR] Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)
                ./dataset_description.json
                        Evidence: .Authors should be array

        Please visit https://neurostars.org/search?q=JSON_SCHEMA_VALIDATION_ERROR for existing conversations about this issue.

        2: [ERR] You have to define 'EchoTime1' and 'EchoTime2' for this file. (code: 15 - ECHO_TIME1-2_NOT_DEFINED)
                ./sub-01/fmap/sub-01_phasediff.nii

        Please visit https://neurostars.org/search?q=ECHO_TIME1-2_NOT_DEFINED for existing conversations about this issue.

        3: [ERR] 'IntendedFor' field needs to point to an existing file. (code: 37 - INTENDED_FOR)
                ./sub-01/fmap/sub-01_magnitude1.nii
                        Evidence: fmap/sub-01_acq-headMTw_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude1.nii
                        Evidence: fmap/sub-01_acq-headPDw_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude1.nii
                        Evidence: fmap/sub-01_acq-headT1w_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude1.nii
                        Evidence: fmap/sub-01_acq-bodyMTw_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude1.nii
                        Evidence: fmap/sub-01_acq-bodyPDw_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude1.nii
                        Evidence: fmap/sub-01_acq-bodyT1w_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude2.nii
                        Evidence: fmap/sub-01_acq-headMTw_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude2.nii
                        Evidence: fmap/sub-01_acq-headPDw_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude2.nii
                        Evidence: fmap/sub-01_acq-headT1w_RB1COR.json
                ./sub-01/fmap/sub-01_magnitude2.nii
                        Evidence: fmap/sub-01_acq-bodyMTw_RB1COR.json
                ... and 8 more files having this issue (Use --verbose to see them all).

        Please visit https://neurostars.org/search?q=INTENDED_FOR for existing conversations about this issue.

        1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

        Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.

        2: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered because there are no authors, which will make DOI registration from dataset metadata impossible. (code: 113 - NO_AUTHORS)

        Please visit https://neurostars.org/search?q=NO_AUTHORS for existing conversations about this issue.

        Summary:                   Available Tasks:        Available Modalities: 
        107 Files, 850.19MB                                MRI                   
        1 - Subject                                                              
        1 - Session                                                              


        If you have any questions, please post on https://neurostars.org/tags/bids.
```

**Comment by Remi-Gau** [comment] 2022-11-08 16:35
same for vfa

```bash
bids-validator ds-vfa 
bids-validator@1.9.9
        1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
                ./sub-01/anat/sub-01_fa-1_VFA.json
                        Evidence: sub-01_fa-1_VFA.json
                ./sub-01/anat/sub-01_fa-1_VFA.nii.gz
                        Evidence: sub-01_fa-1_VFA.nii.gz
                ./sub-01/anat/sub-01_fa-2_VFA.json
                        Evidence: sub-01_fa-2_VFA.json
                ./sub-01/anat/sub-01_fa-2_VFA.nii.gz
                        Evidence: sub-01_fa-2_VFA.nii.gz

        Please visit https://neurostars.org/search?q=NOT_INCLUDED for existing conversations about this issue.

        1: [WARN] NIfTI file's header field for pixel dimension information empty or too short. (code: 42 - NIFTI_PIXDIM)
                ./sub-01/fmap/sub-01_TB1map.nii.gz

        Please visit https://neurostars.org/search?q=NIFTI_PIXDIM for existing conversations about this issue.

        2: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

        Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.

        3: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered based on the presence of only one author field. Please ignore if all contributors are already properly listed. (code: 102 - TOO_FEW_AUTHORS)

        Please visit https://neurostars.org/search?q=TOO_FEW_AUTHORS for existing conversations about this issue.

        Summary:                Available Tasks:        Available Modalities: 
        7 Files, 40.83KB                                MRI                   
        1 - Subject                                                           
        1 - Session                                                           


        If you have any questions, please post on https://neurostars.org/tags/bids.
```

**Comment by Remi-Gau** [comment] 2022-11-08 16:42
The problematic json file in the mpm was fixed in the bids examples and that's why bids matlab can run on CI on it.

https://github.com/bids-standard/bids-examples/blob/master/qmri_mpm/sub-01/fmap/sub-01_magnitude1.json

**Comment by nbeliy** [comment] 2022-11-09 09:24
Sorry for reopening issue, but will it make more sense to just check if referenced file is indexed:
```matlab
if isempty(info_dest.file_idx)
        msg = ['IntendedFor file ' dest ' from ' file.filename ' not indexed'];
        bids.internal.error_handling(mfilename, 'IntendedForMissing', msg, tolerant, verbose);
        continue;
      end
```

Just above the similar check is done for file existence,  and this check is the same (actually it can replace the existance check).

**Comment by nbeliy** [comment] 2022-11-09 13:31
Will do,
side question, how make tests? I don't think modify correct datasets will be a good idea.

I remember there was talks of introduce non-bids datasets as examples, is there some progress there?

**Comment by nbeliy** [comment] 2022-11-09 13:59
Made requests #473 and #474, with two alternative implementation (one with check if file exists other without)

**Comment by Remi-Gau** [comment] 2022-11-11 07:55
> Will do, side question, how make tests? I don't think modify correct datasets will be a good idea.
> 
> I remember there was talks of introduce non-bids datasets as examples, is there some progress there?

yeah I was talking about this again with someone 2 days ago.

there is no official list of bad datasets, so the way I try to handle this is:
- either refactor the code to be able to test the function independently without mocking a whole dataset
- if I REALLY have to I would create a dummy dataset using a bash script (see the bash script in the tests folder). Though I want to change to using python to do this because it would make WAY easier to run the tests on Windows too.

**Closed** 2022-11-11 08:06 UTC
